server:
  port: 8000

logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: postgres # h2/postgres
  application:
    name: job-scheduler


#############

---
spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.default_schema: scheduler
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: scheduler
